---
all:
  children:
    linux_nodes:
      hosts:
        prod-like-node1:
          ansible_host: node1.example.invalid
          ansible_port: 22
        prod-like-node2:
          ansible_host: node2.example.invalid
          ansible_port: 22
  vars:
    ansible_user: devsecops
    ansible_python_interpreter: /usr/bin/python3
