all:
  children:
    linux_nodes:
      hosts:
        linux-node1:
          ansible_host: 127.0.0.1
          ansible_port: 2222
        linux-node2:
          ansible_host: 127.0.0.1
          ansible_port: 2223
  vars:
    ansible_user: devsecops
    ansible_python_interpreter: /usr/bin/python3
